### ISSUE TITLE
ALB Ingress Investigation

### ISSUE THREAD

**Issue by making** [making/kanban#19]

**Comment by making** [comment]
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver
  namespace: echoserver
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-13206548,subnet-134c475a,subnet-895845a1 
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-1:120200614459:certificate/53bb912d-aeb5-42d3-a1dc-96df0a1a7ca9
spec:
  rules:
    - host: echo.bosh.tokyo
      http:
        paths:
          - path: /
            backend:
              serviceName: echoserver
              servicePort: 80
```

Deployed successfully.
